/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppWhatsappRouteImport } from './routes/app.whatsapp'
import { Route as AppTeamRouteImport } from './routes/app.team'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppLogsRouteImport } from './routes/app.logs'
import { Route as AppKnowledgeRouteImport } from './routes/app.knowledge'
import { Route as AppIntegrationsRouteImport } from './routes/app.integrations'
import { Route as AppInboxRouteImport } from './routes/app.inbox'
import { Route as AppDeployRouteImport } from './routes/app.deploy'
import { Route as AppBillingRouteImport } from './routes/app.billing'
import { Route as AppAgentsRouteImport } from './routes/app.agents'
import { Route as AppAdminRouteImport } from './routes/app.admin'
import { Route as AppAgentsIdRouteImport } from './routes/app.agents.$id'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppWhatsappRoute = AppWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamRoute = AppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppLogsRoute = AppLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AppRoute,
} as any)
const AppKnowledgeRoute = AppKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AppRoute,
} as any)
const AppIntegrationsRoute = AppIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AppRoute,
} as any)
const AppInboxRoute = AppInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AppRoute,
} as any)
const AppDeployRoute = AppDeployRouteImport.update({
  id: '/deploy',
  path: '/deploy',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentsRoute = AppAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentsIdRoute = AppAgentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppAgentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/admin': typeof AppAdminRoute
  '/app/agents': typeof AppAgentsRouteWithChildren
  '/app/billing': typeof AppBillingRoute
  '/app/deploy': typeof AppDeployRoute
  '/app/inbox': typeof AppInboxRoute
  '/app/integrations': typeof AppIntegrationsRoute
  '/app/knowledge': typeof AppKnowledgeRoute
  '/app/logs': typeof AppLogsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/team': typeof AppTeamRoute
  '/app/whatsapp': typeof AppWhatsappRoute
  '/app/': typeof AppIndexRoute
  '/app/agents/$id': typeof AppAgentsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/admin': typeof AppAdminRoute
  '/app/agents': typeof AppAgentsRouteWithChildren
  '/app/billing': typeof AppBillingRoute
  '/app/deploy': typeof AppDeployRoute
  '/app/inbox': typeof AppInboxRoute
  '/app/integrations': typeof AppIntegrationsRoute
  '/app/knowledge': typeof AppKnowledgeRoute
  '/app/logs': typeof AppLogsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/team': typeof AppTeamRoute
  '/app/whatsapp': typeof AppWhatsappRoute
  '/app': typeof AppIndexRoute
  '/app/agents/$id': typeof AppAgentsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/admin': typeof AppAdminRoute
  '/app/agents': typeof AppAgentsRouteWithChildren
  '/app/billing': typeof AppBillingRoute
  '/app/deploy': typeof AppDeployRoute
  '/app/inbox': typeof AppInboxRoute
  '/app/integrations': typeof AppIntegrationsRoute
  '/app/knowledge': typeof AppKnowledgeRoute
  '/app/logs': typeof AppLogsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/team': typeof AppTeamRoute
  '/app/whatsapp': typeof AppWhatsappRoute
  '/app/': typeof AppIndexRoute
  '/app/agents/$id': typeof AppAgentsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/admin'
    | '/app/agents'
    | '/app/billing'
    | '/app/deploy'
    | '/app/inbox'
    | '/app/integrations'
    | '/app/knowledge'
    | '/app/logs'
    | '/app/settings'
    | '/app/team'
    | '/app/whatsapp'
    | '/app/'
    | '/app/agents/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/admin'
    | '/app/agents'
    | '/app/billing'
    | '/app/deploy'
    | '/app/inbox'
    | '/app/integrations'
    | '/app/knowledge'
    | '/app/logs'
    | '/app/settings'
    | '/app/team'
    | '/app/whatsapp'
    | '/app'
    | '/app/agents/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/admin'
    | '/app/agents'
    | '/app/billing'
    | '/app/deploy'
    | '/app/inbox'
    | '/app/integrations'
    | '/app/knowledge'
    | '/app/logs'
    | '/app/settings'
    | '/app/team'
    | '/app/whatsapp'
    | '/app/'
    | '/app/agents/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/whatsapp': {
      id: '/app/whatsapp'
      path: '/whatsapp'
      fullPath: '/app/whatsapp'
      preLoaderRoute: typeof AppWhatsappRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/team': {
      id: '/app/team'
      path: '/team'
      fullPath: '/app/team'
      preLoaderRoute: typeof AppTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/logs': {
      id: '/app/logs'
      path: '/logs'
      fullPath: '/app/logs'
      preLoaderRoute: typeof AppLogsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/knowledge': {
      id: '/app/knowledge'
      path: '/knowledge'
      fullPath: '/app/knowledge'
      preLoaderRoute: typeof AppKnowledgeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/integrations': {
      id: '/app/integrations'
      path: '/integrations'
      fullPath: '/app/integrations'
      preLoaderRoute: typeof AppIntegrationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inbox': {
      id: '/app/inbox'
      path: '/inbox'
      fullPath: '/app/inbox'
      preLoaderRoute: typeof AppInboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/deploy': {
      id: '/app/deploy'
      path: '/deploy'
      fullPath: '/app/deploy'
      preLoaderRoute: typeof AppDeployRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/billing': {
      id: '/app/billing'
      path: '/billing'
      fullPath: '/app/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/agents': {
      id: '/app/agents'
      path: '/agents'
      fullPath: '/app/agents'
      preLoaderRoute: typeof AppAgentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/agents/$id': {
      id: '/app/agents/$id'
      path: '/$id'
      fullPath: '/app/agents/$id'
      preLoaderRoute: typeof AppAgentsIdRouteImport
      parentRoute: typeof AppAgentsRoute
    }
  }
}

interface AppAgentsRouteChildren {
  AppAgentsIdRoute: typeof AppAgentsIdRoute
}

const AppAgentsRouteChildren: AppAgentsRouteChildren = {
  AppAgentsIdRoute: AppAgentsIdRoute,
}

const AppAgentsRouteWithChildren = AppAgentsRoute._addFileChildren(
  AppAgentsRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppAgentsRoute: typeof AppAgentsRouteWithChildren
  AppBillingRoute: typeof AppBillingRoute
  AppDeployRoute: typeof AppDeployRoute
  AppInboxRoute: typeof AppInboxRoute
  AppIntegrationsRoute: typeof AppIntegrationsRoute
  AppKnowledgeRoute: typeof AppKnowledgeRoute
  AppLogsRoute: typeof AppLogsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTeamRoute: typeof AppTeamRoute
  AppWhatsappRoute: typeof AppWhatsappRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppAgentsRoute: AppAgentsRouteWithChildren,
  AppBillingRoute: AppBillingRoute,
  AppDeployRoute: AppDeployRoute,
  AppInboxRoute: AppInboxRoute,
  AppIntegrationsRoute: AppIntegrationsRoute,
  AppKnowledgeRoute: AppKnowledgeRoute,
  AppLogsRoute: AppLogsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTeamRoute: AppTeamRoute,
  AppWhatsappRoute: AppWhatsappRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
